### ISSUE TITLE
Login no Google detectado como malicioso

### ISSUE THREAD

**Issue by mAngelo-dev** [michaelcaxias/trybe-schedule#55]
Quando clicado para fazer login, aparece a seguinte mensagem ![image](https://user-images.githubusercontent.com/84293279/180577321-b2368bb4-9127-47da-a29b-cc202264baa9.png)

**Comment by mAngelo-dev** [comment]
Com a API 1 dá a mesma coisa 
![image](https://user-images.githubusercontent.com/84293279/180577410-12d31af0-44dc-4e76-a9c6-5467e227d4fb.png)

**Comment by michaelcaxias** [comment]
Isso se dá devido ao fato do google não ter verificado a aplicação.. Clique no canto superior direito, acesse a API 2 e conseguirá acessar normalmente.

![image](https://user-images.githubusercontent.com/79621661/180615175-fff32d03-bdc7-4f8b-b63c-06cff3f5052d.png)

**Comment by michaelcaxias** [comment]
Esse problema ocorre nas APIs por conta da falta de verificação do Google. Na API 2, basta clicar em "Avançado"  e acessar normalmente, já na API 1 ocorre por conta do limite de 100 usuários do google (que já foi ultrapassado nessa api)
